services:
  # Laravel App (PHP-FPM)
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=healthinsurance
      - DB_USERNAME=qsoft
      - DB_PASSWORD=Time@12345
    ports:
      - "9000:9000"

  # Nginx Web server
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthinsurance
      POSTGRES_USER: qsoft
      POSTGRES_PASSWORD: Time@12345
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qsoft"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  laravel_network:
    driver: bridge

volumes:
  pg_data:
    driver: local

